ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"      
  hosts:
    primaryHost: 
      domain: luna.local
    identityHost: 
      domain: identity.luna.local
    chromeleonIdpHost: 
      domain: cmidp.luna.local
    apiHost: 
      domain: api.luna.local
  tls: 
   - secretName: luna-tls-secret
     hosts:
       - luna.local  
   - secretName: luna-identity-tls-secret
     hosts:       
       - identity.luna.local    
   - secretName: luna-cmidp-tls-secret 
     hosts:           
       - cmidp.luna.local
   - secretName: luna-api-tls-secret
     hosts:             
       - api.luna.local      

globalConfig:
  postgresql:
    externalServer: host.domain
    externalServerPassword: <PASSWORD>

  
