/*************************************************************************
Output File 
*************************************************************************/

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "workers_asg_arns" {
  description = "IDs of the autoscaling groups containing linux workers."
  value = module.eks.*.workers_asg_arns
}

output "workers_asg_names" {
  description = "Names of the autoscaling groups containing workers."
  value = module.eks.workers_asg_arns
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

output "cluster_name" {
  description = "The name of the EKS Cluster Deployed."
  value       = "${local.cluster-name}"
}

# VPC
output "vpc_id" {
  description = "The ID of the VPC"
  value       =  module.vpc.vpc_id
}

# Subnets
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "aws_account_id" {
  value = var.aws-account-num
}

output "cluster-autoscaling-policy-name" {
  value = "cluster-autoscaler-${random_string.this.id}"
}


